const enChamps = [
    {
        champName: 'Akali',
        splashSrc: './assets/champs/akali/splash.jpg',
        splashShortSrc: './assets/champs/akali/200x500.jpg',
        champSoundSrc: './assets/champs/akali/sound__en.mp3',
        option: 'female',
        champDescription: 'Abandoning the Kinkou Order and her title of the Fist of Shadow, Akali now strikes alone, ready to be the deadly weapon her people need. Though she holds onto all she learned from her master Shen, she has pledged to defend Ionia from its enemies, one kill at a time. Akali may strike in silence, but her message will be heard loud and clear: fear the assassin with no master.',
    },
    {
        champName: 'Ashe',
        splashSrc: './assets/champs/ashe/splash.jpg',
        splashShortSrc: './assets/champs/ashe/200x500.jpg',
        champSoundSrc: './assets/champs/ashe/sound__en.mp3',
        option: 'female',
        champDescription: 'Iceborn warmother of the Avarosan tribe, Ashe commands the most populous horde in the north. Stoic, intelligent, and idealistic, yet uncomfortable with her role as leader, she taps into the ancestral magics of her lineage to wield a bow of True Ice. With her people’s belief that she is the mythological hero Avarosa reincarnated, Ashe hopes to unify the Freljord once more by retaking their ancient, tribal lands.',
    },
    {
        champName: 'Diana',
        splashSrc: './assets/champs/diana/splash.jpg',
        splashShortSrc: './assets/champs/diana/200x500.jpg',
        champSoundSrc: './assets/champs/diana/sound__en.mp3',
        option: 'female',
        champDescription: 'Bearing her crescent moonblade and clad in shimmering armor the color of winter snow at night, Diana is a living embodiment of the silver moon’s power. Imbued with the essence of an Aspect from beyond Targon’s towering summit, Diana is no longer wholly human, and struggles to understand her power and purpose in this world.',
    },
    {
        champName: "Kai'Sa",
        splashSrc: './assets/champs/kaisa/splash.jpg',
        splashShortSrc: './assets/champs/kaisa/200x500.jpg',
        champSoundSrc: './assets/champs/kaisa/sound__en.mp3',
        option: 'female',
        champDescription: "Claimed by the Void when she was only a child, Kai'Sa managed to survive through sheer tenacity and strength of will. Her experiences have made her a deadly hunter and, to some, the harbinger of a future they would rather not live to see. Having entered into an uneasy symbiosis with a living Void carapace, the time will soon come when she must decide whether to forgive those mortals who would call her a monster, and defeat the coming darkness together… or simply to forget, as the Void consumes the world that left her behind.",
    },
    {
        champName: 'Katarina',
        splashSrc: './assets/champs/katarina/splash.jpg',
        splashShortSrc: './assets/champs/katarina/200x500.jpg',
        champSoundSrc: './assets/champs/katarina/sound__en.mp3',
        option: 'female',
        champDescription: 'Decisive in judgment and lethal in combat, Katarina is a Noxian assassin of the highest caliber. Eldest daughter to the legendary General Du Couteau, she made her talents known with swift kills against unsuspecting enemies. Her fiery ambition has driven her to pursue heavily-guarded targets, even at the risk of endangering her allies—but no matter the mission, Katarina will not hesitate to execute her duty amid a whirlwind of serrated daggers.',
    },
    {
        champName: 'Miss Fortune',
        splashSrc: './assets/champs/miss-fortuna/splash.jpg',
        splashShortSrc: './assets/champs/miss-fortuna/200x500.jpg',
        champSoundSrc: './assets/champs/miss-fortuna/sound__en.mp3',
        option: 'female',
        champDescription: 'A Bilgewater captain famed for her looks but feared for her ruthlessness, Sarah Fortune paints a stark figure among the hardened criminals of the port city. As a child, she witnessed the reaver king Gangplank murder her family—an act she brutally avenged years later, blowing up his flagship while he was still aboard. Those who underestimate her will face a beguiling and unpredictable opponent… and, likely, a bullet or two in their guts.',
    },
    {
        champName: 'Nidalee',
        splashSrc: './assets/champs/nidali/splash.jpg',
        splashShortSrc: './assets/champs/nidali/200x500.jpg',
        champSoundSrc: './assets/champs/nidali/sound__en.mp3',
        option: 'female',
        champDescription: 'Raised in the deepest jungle, Nidalee is a master tracker who can shapeshift into a ferocious cougar at will. Neither wholly woman nor beast, she viciously defends her territory from any and all trespassers, with carefully placed traps and deft spear throws. She cripples her quarry before pouncing on them in feline form—the lucky few who survive tell tales of a wild woman with razor-sharp instincts, and even sharper claws...',
    },
    {
        champName: 'Riven',
        splashSrc: './assets/champs/riven/splash.jpg',
        splashShortSrc: './assets/champs/riven/200x500.jpg',
        champSoundSrc: './assets/champs/riven/sound__en.mp3',
        option: 'female',
        champDescription: 'Once a swordmaster in the warhosts of Noxus, Riven rose through the ranks on the strength of her conviction and brutal efficiency, and was rewarded with a legendary runic blade and a warband of her own. However, on the Ionian front, Riven’s faith in her nation was tested and ultimately broken. She severed all ties to the empire, seeking to find her place in a shattered world, even as rumors abounded that Noxus had been reforged. Now forced to return in chains, she faces the judgment of her former homeland...',
    },
    {
        champName: 'Samira',
        splashSrc: './assets/champs/samira/splash.jpg',
        splashShortSrc: './assets/champs/samira/200x500.jpg',
        champSoundSrc: './assets/champs/samira/sound__en.mp3',
        option: 'female',
        champDescription: 'Samira stares death in the eye with unyielding confidence, seeking thrill wherever she goes. After her Shuriman home was destroyed as a child, Samira found her true calling in Noxus, where she built a reputation as a stylish daredevil taking on dangerous missions of the highest caliber. Wielding black-powder pistols and a custom-engineered blade, Samira thrives in life-or-death circumstances, eliminating any who stand in her way with flash and flair.',
    },
    {
        champName: 'Senna',
        splashSrc: './assets/champs/senna/splash.jpg',
        splashShortSrc: './assets/champs/senna/200x500.jpg',
        champSoundSrc: './assets/champs/senna/sound__en.mp3',
        option: 'female',
        champDescription: 'Cursed from childhood to be haunted by the supernatural Black Mist, Senna joined a sacred order known as the Sentinels of Light, and fiercely fought back—only to be killed, her soul imprisoned in a lantern by the cruel wraith Thresh. But refusing to lose hope, within the lantern Senna learned to use the Mist, and reemerged to new life, forever changed. Now wielding darkness along with light, Senna seeks to end the Black Mist by turning it against itself—with every blast of her relic weapon, redeeming the souls lost within.',
    },
    {
        champName: 'Soraka',
        splashSrc: './assets/champs/soraka/splash.jpg',
        splashShortSrc: './assets/champs/soraka/200x500.jpg',
        champSoundSrc: './assets/champs/soraka/sound__en.mp3',
        option: 'female',
        champDescription: "Awanderer from the celestial realm, Soraka gave up her immortal form to protect the mortal races from their own ignorance and violent instincts. She endeavors to spread the virtues of compassion and mercy to everyone she meets—guiding the lost, and healing the wounded. For all Soraka has seen of this world's struggles, she still believes the people of Runeterra have yet to reach their full potential.",
    },
    {
        champName: 'Vayne',
        splashSrc: './assets/champs/vayne/splash.jpg',
        splashShortSrc: './assets/champs/vayne/200x500.jpg',
        champSoundSrc: './assets/champs/vayne/sound__en.mp3',
        option: 'female',
        champDescription: 'Shauna Vayne is a deadly, remorseless Demacian monster hunter, who has dedicated her life to finding and destroying the demon that murdered her family. Armed with a wrist-mounted crossbow and a heart full of vengeance, she is only truly happy when slaying practitioners or creations of the dark arts, striking from the shadows with a flurry of silver bolts.',
    },
    {
        champName: 'Master Yi',
        splashSrc: './assets/champs/master-yi/splash.jpg',
        splashShortSrc: './assets/champs/master-yi/200x500.jpg',
        champSoundSrc: './assets/champs/master-yi/sound__en.mp3',
        option: 'male',
        champDescription: 'Master Yi has tempered his body and sharpened his mind, so that thought and action have become almost as one. Though he chooses to enter into violence only as a last resort, the grace and speed of his blade ensures resolution is always swift. As one of the last living practitioners of the Ionian art of Wuju, Yi has devoted his life to continuing the legacy of his people—scrutinizing potential new disciples with the Seven Lenses of Insight to identify the most worthy among them.',
    },
    {
        champName: 'Talon',
        splashSrc: './assets/champs/talon/splash.jpg',
        splashShortSrc: './assets/champs/talon/200x500.jpg',
        champSoundSrc: './assets/champs/talon/sound__en.mp3',
        option: 'male',
        champDescription: 'Talon is the knife in the darkness, a merciless killer able to strike without warning and escape before any alarm is raised. He carved out a dangerous reputation on the brutal streets of Noxus, where he was forced to fight, kill, and steal to survive. Adopted by the notorious Du Couteau family, he now plies his deadly trade at the empire’s command, assassinating enemy leaders, captains, and heroes… as well as any Noxian foolish enough to earn the scorn of their masters.',
    },
    {
        champName: 'Yasuo',
        splashSrc: './assets/champs/yasuo/splash.jpg',
        splashShortSrc: './assets/champs/yasuo/200x500.jpg',
        champSoundSrc: './assets/champs/yasuo/sound__en.mp3',
        option: 'male',
        champDescription: 'An Ionian of deep resolve, Yasuo is an agile swordsman who wields the air itself against his enemies. As a proud young man, he was falsely accused of murdering his master—unable to prove his innocence, he was forced to slay his own brother in self-defense. In time, his master’s true killer was revealed, and his brother mysteriously returned from death, yet Yasuo still could not forgive himself for all he had done. Now, he wanders the world with only the wind to guide his blade.',
    },
    {
        champName: 'Yone',
        splashSrc: './assets/champs/yone/splash.jpg',
        splashShortSrc: './assets/champs/yone/200x500.jpg',
        champSoundSrc: './assets/champs/yone/sound__en.mp3',
        option: 'male',
        champDescription: 'In life, he was Yone—half-brother of Yasuo, and renowned student of his village’s sword school. But upon his death at the hands of his brother, he found himself hunted by a malevolent entity of the spirit realm, and was forced to slay it with its own sword. Now, cursed to wear its demonic mask upon his face, Yone tirelessly hunts all such creatures in order to understand what he has become.',
    },
    {
        champName: 'Zak',
        splashSrc: './assets/champs/zak/splash.jpg',
        splashShortSrc: './assets/champs/zak/200x500.jpg',
        champSoundSrc: './assets/champs/zak/sound__en.mp3',
        option: 'male',
        champDescription: 'Zac is the product of a toxic spill that ran through a chemtech seam and pooled in an isolated cavern deep in Zaun’s Sump. Despite such humble origins, Zac has grown from primordial ooze into a thinking being who dwells in the city’s pipes, occasionally emerging to help those who cannot help themselves or to rebuild the broken infrastructure of Zaun.',
    },
    {
        champName: 'Dr. Mundo',
        splashSrc: './assets/champs/dr-mundo/splash.jpg',
        splashShortSrc: './assets/champs/dr-mundo/200x500.jpg',
        champSoundSrc: './assets/champs/dr-mundo/sound__en.mp3',
        option: 'male',
        champDescription: 'Utterly mad, tragically homicidal, and horrifyingly purple, Dr. Mundo is what keeps many of Zaun’s citizens indoors on particularly dark nights. Now a self-proclaimed physician, he was once a patient of Zaun’s most infamous asylum. After “curing” the entire staff, Dr. Mundo established his practice in the empty wards that once treated him and began mimicking the highly unethical procedures he had so often experienced himself. With a full cabinet of medicines and zero medical knowledge, he now makes himself more monstrous with each injection and terrifies the hapless “patients” who wander near his office.',
    },
    {
        champName: 'Alistar',
        splashSrc: './assets/champs/alistar/splash.jpg',
        splashShortSrc: './assets/champs/alistar/200x500.jpg',
        champSoundSrc: './assets/champs/alistar/sound__en.mp3',
        option: 'spirit',
        champDescription: 'lways a mighty warrior with a fearsome reputation, Alistar seeks revenge for the death of his clan at the hands of the Noxian empire. Though he was enslaved and forced into the life of a gladiator, his unbreakable will was what kept him from truly becoming a beast. Now, free of the chains of his former masters, he fights in the name of the downtrodden and the disadvantaged, his rage as much a weapon as his horns, hooves and fists.',
    },
    {
        champName: 'Azir',
        splashSrc: './assets/champs/azir/splash.jpg',
        splashShortSrc: './assets/champs/azir/200x500.jpg',
        champSoundSrc: './assets/champs/azir/sound__en.mp3',
        option: 'spirit',
        champDescription: 'Azir was a mortal emperor of Shurima in a far distant age, a proud man who stood at the cusp of immortality. His hubris saw him betrayed and murdered at the moment of his greatest triumph, but now, millennia later, he has been reborn as an Ascended being of immense power. With his buried city risen from the sand, Azir seeks to restore Shurima to its former glory.',
    },
    {
        champName: 'Kindred',
        splashSrc: './assets/champs/kindred/splash.jpg',
        splashShortSrc: './assets/champs/kindred/200x500.jpg',
        champSoundSrc: './assets/champs/kindred/sound__en.mp3',
        option: 'spirit',
        champDescription: 'Separate, but never parted, Kindred represents the twin essences of death. Lamb’s bow offers a swift release from the mortal realm for those who accept their fate. Wolf hunts down those who run from their end, delivering violent finality within his crushing jaws. Though interpretations of Kindred’s nature vary across Runeterra, every mortal must choose the true face of their death.',
    },
    {
        champName: 'Malphite',
        splashSrc: './assets/champs/malphit/splash.jpg',
        splashShortSrc: './assets/champs/malphit/200x500.jpg',
        champSoundSrc: './assets/champs/malphit/sound__en.mp3',
        option: 'spirit',
        champDescription: 'A massive creature of living stone, Malphite was born from the heart of the great Ixtali construct known as the Monolith. He has studied the elemental balance of Runeterra for centuries, using his tremendous strength to maintain order in a frequently chaotic world, and crush the dark things that crawl beneath it. Now, roused all too often from his slumbers, Malphite endures the fluid temperaments of mortals, in pursuit of the only cause worthy of the last of his kind.',
    },
    {
        champName: 'Nasus',
        splashSrc: './assets/champs/nasus/splash.jpg',
        splashShortSrc: './assets/champs/nasus/200x500.jpg',
        champSoundSrc: './assets/champs/nasus/sound__en.mp3',
        option: 'spirit',
        champDescription: 'Nasus is an imposing, jackal-headed Ascended—those heroic and god-like figures once revered by the people of Shurima. Fiercely intelligent, he was a guardian of knowledge and peerless strategist whose wisdom guided the empire to greatness for many centuries. After the failed Ascension of Azir, Nasus went into self-imposed exile, becoming little more than a legend. Now that the Sun Disc has risen once more, he has returned, determined to ensure it never falls again.',
    },
    {
        champName: 'Ornn',
        splashSrc: './assets/champs/orn/splash.jpg',
        splashShortSrc: './assets/champs/orn/200x500.jpg',
        champSoundSrc: './assets/champs/orn/sound__en.mp3',
        option: 'spirit',
        champDescription: 'Ornn is the Freljordian demi-god of forging and craftsmanship. He works in the solitude of a massive smithy, hammered out from the lava caverns beneath the volcano Hearth-Home. There he stokes bubbling cauldrons of molten rock to purify ores and fashion items of unsurpassed quality. When other deities—especially Volibear—walk the earth and meddle in mortal affairs, Ornn arises to put these impetuous beings back in their place, either with his trusty hammer or the fiery power of the mountains themselves.',
    },
    {
        champName: 'Nocturne',
        splashSrc: './assets/champs/nocturn/splash.jpg',
        splashShortSrc: './assets/champs/nocturn/200x500.jpg',
        champSoundSrc: './assets/champs/nocturn/sound__en.mp3',
        option: 'spirit',
        champDescription: 'A demonic amalgamation drawn from the nightmares that haunt every sentient mind, the thing known as Nocturne has become a primordial force of pure terror. It is liquidly chaotic in aspect, a faceless shadow with cold eyes and armed with wicked-looking blades. After freeing itself from the spirit realm, Nocturne now continually descends upon the waking world, to feed on the kind of fear that can only thrive in true darkness.',
    },
    {
        champName: 'Tahm Kench',
        splashSrc: './assets/champs/taam-kench/splash.jpg',
        splashShortSrc: './assets/champs/taam-kench/200x500.jpg',
        champSoundSrc: './assets/champs/taam-kench/sound__en.mp3',
        option: 'spirit',
        champDescription: 'Known by many names throughout history, the demon Tahm Kench travels the waterways of Runeterra, feeding his insatiable appetite with the misery of others. Though he may appear singularly charming and proud, he swaggers through the physical realm like a vagabond in search of unsuspecting prey. His lashing tongue can stun even a heavily armored warrior from a dozen paces, and to fall into his rumbling belly is to tumble into an abyss from which there is little hope of return.',
    },
    {
        champName: 'Renekton',
        splashSrc: './assets/champs/renecton/splash.jpg',
        splashShortSrc: './assets/champs/renecton/200x500.jpg',
        champSoundSrc: './assets/champs/renecton/sound__en.mp3',
        option: 'spirit',
        champDescription: 'Renekton is a terrifying, rage-fueled Ascended warrior from the scorched deserts of Shurima. Once, he was his empire’s most esteemed champion, leading its grand armies to countless victories. However, after the fall of the Sun Disc, Renekton was entombed beneath the sands—and slowly, as the world above changed, he succumbed to insanity. Now free once more, he is utterly consumed with wreaking vengeance upon his brother, Nasus, who he blames for the centuries lost in darkness.',
    },
    {
        champName: 'Thresh',
        splashSrc: './assets/champs/thresh/splash.jpg',
        splashShortSrc: './assets/champs/thresh/200x500.jpg',
        champSoundSrc: './assets/champs/thresh/sound__en.mp3',
        option: 'spirit',
        champDescription: 'Sadistic and cunning, Thresh is an ambitious and restless spirit of the Shadow Isles. Once the custodian of countless arcane secrets, he was undone by a power greater than life or death, and now sustains himself by tormenting and breaking others with slow, excruciating inventiveness. His victims suffer far beyond their brief mortal coil as Thresh wreaks agony upon their souls, imprisoning them in his unholy lantern to torture for all eternity.',
    },
    {
        champName: 'Volibear',
        splashSrc: './assets/champs/volibir/splash.jpg',
        splashShortSrc: './assets/champs/volibir/200x500.jpg',
        champSoundSrc: './assets/champs/volibir/sound__en.mp3',
        option: 'spirit',
        champDescription: 'To those who still revere him, the Volibear is the storm made manifest. Destructive, wild, and stubbornly resolute, he existed before mortals walked the Freljord’s tundra, and is fiercely protective of the lands that he and his demi-god kin created. Cultivating a deep hatred of civilization and the weakness it brought with it, he now fights to return to the old ways—when the land was untamed, and blood spilled freely—and eagerly battles all who oppose him, with tooth, claw, and thundering domination.',
    },
    {
        champName: 'Yorick',
        splashSrc: './assets/champs/yorick/splash.jpg',
        splashShortSrc: './assets/champs/yorick/200x500.jpg',
        champSoundSrc: './assets/champs/yorick/sound__en.mp3',
        option: 'spirit',
        champDescription: 'The last survivor of a long-forgotten religious order, Yorick is both blessed and cursed with power over the dead. Trapped on the Shadow Isles, his only companions are the rotting corpses and shrieking spirits that he gathers to him. Yorick’s monstrous actions belie his noble purpose: to free his home from the curse of the Ruination.',
    },
    {
        champName: 'Warwick',
        splashSrc: './assets/champs/warwick/splash.jpg',
        splashShortSrc: './assets/champs/warwick/200x500.jpg',
        champSoundSrc: './assets/champs/warwick/sound__en.mp3',
        option: 'spirit',
        champDescription: 'Warwick is a monster who hunts the gray alleys of Zaun. Transformed by agonizing experiments, his body is fused with an intricate system of chambers and pumps, machinery filling his veins with alchemical rage. Bursting out of the shadows, he preys upon those criminals who terrorize the city’s depths. Warwick is drawn to blood, and driven mad by its scent. None who spill it can escape him.',
    },
    {
        champName: 'Rengar',
        splashSrc: './assets/champs/rengar/splash.jpg',
        splashShortSrc: './assets/champs/rengar/200x500.jpg',
        champSoundSrc: './assets/champs/rengar/sound__en.mp3',
        option: 'spirit',
        champDescription: 'Rengar is a ferocious vastayan trophy hunter who lives for the thrill of tracking down and killing dangerous creatures. He scours the world for the most fearsome beasts he can find, especially seeking any trace of Kha’Zix, the void creature who scratched out his eye. Rengar stalks his prey neither for food nor glory, but for the sheer beauty of the pursuit.',
    },
    {
        champName: 'Gnar',
        splashSrc: './assets/champs/gnar/splash.jpg',
        splashShortSrc: './assets/champs/gnar/200x500.jpg',
        champSoundSrc: './assets/champs/gnar/sound-v1.mp3',
        option: 'spirit',
        champDescription: "Gnar is a primeval yordle whose playful antics can erupt into a toddler's outrage in an instant, transforming him into a massive beast bent on destruction. Frozen in True Ice for millennia, the curious creature broke free and now hops about a changed world he sees as exotic and wondrous. Delighted by danger, Gnar flings whatever he can at his enemies, be it his bonetooth boomerang, or a nearby building.",
    },
    {
        champName: 'Fizz',
        splashSrc: './assets/champs/fizz/splash.jpg',
        splashShortSrc: './assets/champs/fizz/200x500.jpg',
        champSoundSrc: './assets/champs/fizz/sound__en.mp3',
        option: 'yordle',
        champDescription: 'Fizz is an amphibious yordle, who dwells among the reefs surrounding Bilgewater. He often retrieves and returns the tithes cast into the sea by superstitious captains, but even the saltiest of sailors know better than to cross him—for many are the tales of those who have underestimated this slippery character. Often mistaken for some manner of capricious ocean spirit, he seems able to command the beasts of the deep, and delights in confounding his allies and enemies alike.',
    },
    {
        champName: 'Teemo',
        splashSrc: './assets/champs/teemo/splash.jpg',
        splashShortSrc: './assets/champs/teemo/200x500.jpg',
        champSoundSrc: './assets/champs/teemo/sound__en.mp3',
        option: 'yordle',
        champDescription: "Undeterred by even the most dangerous and threatening of obstacles, Teemo scouts the world with boundless enthusiasm and a cheerful spirit. A yordle with an unwavering sense of morality, he takes pride in following the Bandle Scout's Code, sometimes with such eagerness that he is unaware of the broader consequences of his actions. Though some say the existence of the Scouts is questionable, one thing is for certain: Teemo's conviction is nothing to be trifled with.",
    },
    {
        champName: 'Twitch',
        splashSrc: './assets/champs/twitch/splash.jpg',
        splashShortSrc: './assets/champs/twitch/200x500.jpg',
        champSoundSrc: './assets/champs/twitch/sound__en.mp3',
        option: 'yordle',
        champDescription: 'A Zaunite plague rat by birth, but a connoisseur of filth by passion, Twitch is not afraid to get his paws dirty. Aiming a chem-powered crossbow at the gilded heart of Piltover, he has vowed to show those in the city above just how filthy they really are. Always a sneaky sneak, when he’s not rooting around in the Sump, he’s digging deep into other people’s garbage for discarded treasures… and perhaps a moldy sandwich.',
    },
    {
        champName: 'Ziggs',
        splashSrc: './assets/champs/ziggs/splash.jpg',
        splashShortSrc: './assets/champs/ziggs/200x500.jpg',
        champSoundSrc: './assets/champs/ziggs/sound__en.mp3',
        option: 'yordle',
        champDescription: 'With a love of big bombs and short fuses, the yordle Ziggs is an explosive force of nature. As an inventor’s assistant in Piltover, he was bored by his predictable life and befriended a mad, blue-haired bomber named Jinx. After a wild night on the town, Ziggs took her advice and moved to Zaun, where he now explores his fascinations more freely, terrorizing the chem-barons and regular citizens alike in his never ending quest to blow stuff up.',
    },
    {
        champName: 'Kennen',
        splashSrc: './assets/champs/kennen/splash.jpg',
        splashShortSrc: './assets/champs/kennen/200x500.jpg',
        champSoundSrc: './assets/champs/kennen/sound__en.mp3',
        option: 'yordle',
        champDescription: 'The longest-standing member of the ancient Kinkou Order, the yordle Kennen is the first and only Heart of the Tempest. For centuries, he has used diplomacy—and force—to maintain the sacred balance in his adopted home of Ionia. Lightning fast and bearing the wisdom of a long and storied life, Kennen works with the Eye of Twilight, Shen, to protect the fragile harmony of the First Lands with a whirling storm of shuriken and devastating electrical energy.',
    },
    {
        champName: 'Gnar',
        splashSrc: './assets/champs/gnar/splash.jpg',
        splashShortSrc: './assets/champs/gnar/200x500.jpg',
        champSoundSrc: './assets/champs/gnar/sound__en.mp3',
        option: 'yordle',
        champDescription: "Gnar is a primeval yordle whose playful antics can erupt into a toddler's outrage in an instant, transforming him into a massive beast bent on destruction. Frozen in True Ice for millennia, the curious creature broke free and now hops about a changed world he sees as exotic and wondrous. Delighted by danger, Gnar flings whatever he can at his enemies, be it his bonetooth boomerang, or a nearby building.",
    },
]

export default enChamps